# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CN8aq8-VFCDVVV9r1-D94qLw8sSvHdxr
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv('data.csv')

data.info()

data.shape

data.isnull().sum()

data.drop('Unnamed: 32',axis=1,inplace=True)



data.describe()

data.drop('id',axis=1,inplace=True)

data.shape

var=data.columns

var

data['diagnosis']=data['diagnosis'].astype('category')

data['Diagnosis']=data['diagnosis'].cat.codes

data.head()

sns.countplot(data['diagnosis'])

data.info()

plt.figure(figsize=(15,15))
for i,var in enumerate(data):
  plt.subplot(11,3,i+1)
  sns.distplot(data[var],kde=True,bins=20)

data.drop('diagnosis',axis=1,inplace=True)

data.head()

datadf=data.iloc[:,0:30]

datadf

datadf.shape

from sklearn.preprocessing import  StandardScaler

Scaler=StandardScaler()

scale=Scaler.fit_transform(datadf)

data1=pd.DataFrame(scale,columns=datadf.columns)

data1.describe()

plt.figure(figsize=(15,15))
for i,var in enumerate(data1):
  plt.subplot(11,3,i+1)
  sns.distplot(data[var],kde=True,bins=20)

fig=plt.figure(figsize=(10,12))
ax2=fig.add_axes([0,0,1,1])
for i,var in enumerate(data1):
  sns.kdeplot(data1[var],ax=ax2)

